apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "amazon-network-policy-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "amazon-network-policy-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
